let myDate=new Date("2025-04-16");
//console.log(myDate.toString());
// console.log(myDate.toISOString());
// console.log(myDate.toJSON());
// console.log(myDate.toTimeString());
 //console.log(myDate.toLocaleString());
// console.log(myDate.toLocaleTimeString());
console.log(myDate.getDate());
console.log(myDate.getHours());
console.log(myDate.getMonth()+1);
